minimum_pre_commit_version: 3.7.0
default_install_hook_types:
  - commit-msg
  - pre-push
default_stages: 
    - commit-msg
    - pre-push

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: end-of-file-fixer
        name: add-empty-line-to-end-of-file

-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
    -   id: remove-tabs
        name: replace-tabs-with-spaces
        args: [--whitespaces-count, '4']

-   repo: https://github.com/asottile/reorder-python-imports
    rev: v3.12.0
    hooks:
    -   id: reorder-python-imports
        name: reorder-python-imports
        entry: env PYTHONPATH='' reorder-python-imports

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.2
    hooks:
    -   id: ruff
        name: ruff-check

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.2
    hooks:
    -   id: ruff-format
        name: ruff-format
        entry: ruff format --config pyproject.toml

-   repo: local
    hooks:
    -   id: run-tests
        name: run-tests
        entry: pytest
        language: python
        types: [python]
        pass_filenames: false
        always_run: true
        stages: [pre-push]
        additional_dependencies: 
            - "pytest>=8.2.0"
            - "commitizen>=3.27.0"
            - "tomli>=2.0.1"
